#
# fetch .tar.gz files
#

- stat:
    path: "{{ java_downloaded_path }}/{{ jdk_tarball_file }}"
  register: st

- debug: var=st

- debug: msg="Download {{ jdk_tarball_url }} to {{ java_downloaded_path }}/{{ jdk_tarball_file }}"

- name: get JDK tarball (as tar.gz file)
  get_url:
    url:     "{{ jdk_tarball_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_downloaded_path }}/{{ jdk_tarball_file }}"
    mode:    0644
  when: not st.stat.exists

- block:
  - stat:
      path: "{{ java_downloaded_path }}/{{ jce_zip_file }}"
    register: st2

  - debug: msg="Download {{ jce_zip_url }} to {{ java_downloaded_path }}/{{ jce_zip_file }}"

  - name: get JCE
    get_url:
      url:     "{{ jce_zip_url }}"
      headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
      dest:    "{{ java_downloaded_path }}/{{ jce_zip_file }}"
      mode:    0644
    when: not st2.stat.exists
  when: java_install_jce
