---
# file: use-tarball.yml
# install Oracle JDK 1.x on distributions other than the CentOS/RHEL family
#
# See: https://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_jdk.html
#

- name: mkdir for Java
  file:
    path: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: Copy tar.gz
  copy:
    src: "{{ java_downloaded_path }}/{{ jdk_tarball_file }}"
    dest: "{{ java_tmp_path }}/{{ jdk_tarball_file }}"
    mode: "0644"

- name: install JDK via tarball file
  unarchive:
    src: "{{ java_tmp_path }}/{{ jdk_tarball_file }}"
    dest: "{{ java_install_dir }}"
    owner: root
    group: root
    mode: "go-w"
    copy: no
